apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.release.name}}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.release.host }}
    secretName: {{ .Values.release.secretTLS}}
  rules:
  - host: {{ .Values.release.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.release.name}}
          servicePort: {{ .Values.release.port }}
