apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release.name}}
  namespace: {{ .Values.release.namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.release.port}}
      targetPort: {{ .Values.release.port}}
  selector:
    app: {{ .Values.release.name}}